import java.util.HashMap;

public class RomanResult {

static HashMap<Integer,String>result=new HashMap<Integer, String>();
static {
    result.put(0,"0");
    result.put(1, "I");
    result.put(2, "II");
    result.put(3, "III");
    result.put(4, "IV");
    result.put(5,"V");
    result.put(6,"VI");
    result.put(7,"VII");
    result.put(8,"VIII");
    result.put(9,"IX");
    result.put(10,"X");
    result.put(11, "XI");
    result.put(12, "XII");
    result.put(13, "XIII");
    result.put(14, "XIV");
    result.put(15,"XV");
    result.put(16,"XVI");
    result.put(17,"XVII");
    result.put(18,"XVIII");
    result.put(19,"XIX");
    result.put(20,"XX");
    result.put(21, "XXI");
    result.put(22, "XXII");
    result.put(23, "XXIII");
    result.put(24, "XXIV");
    result.put(25,"XXV");
    result.put(26,"XXVI");
    result.put(27,"XXVII");
    result.put(28,"XXVIII");
    result.put(29,"XXIX");
    result.put(30,"XXX");
    result.put(31, "XXXI");
    result.put(32, "XXXII");
    result.put(33, "XXXIII");
    result.put(34, "XXXIV");
    result.put(35,"XXXV");
    result.put(36,"XXXVI");
    result.put(37,"XXXVII");
    result.put(38,"XXXVIII");
    result.put(39,"XXXIX");
    result.put(40,"XL");
    result.put(41, "XLI");
    result.put(42, "XLII");
    result.put(43, "XLIII");
    result.put(44, "XLIV");
    result.put(45,"XLV");
    result.put(46,"XLVI");
    result.put(47,"XLVII");
    result.put(48,"XLVIII");
    result.put(49,"XLIX");
    result.put(50,"L");
    result.put(51, "LI");
    result.put(52, "LII");
    result.put(53, "LIII");
    result.put(54, "LIV");
    result.put(55,"LV");
    result.put(56,"LVI");
    result.put(57,"LVII");
    result.put(58,"LVIII");
    result.put(59,"LIX");
    result.put(60,"LX");
    result.put(61, "LXI");
    result.put(62, "LXII");
    result.put(63, "LXIII");
    result.put(64, "LXIV");
    result.put(65,"LXV");
    result.put(66,"LXVI");
    result.put(67,"LXVII");
    result.put(68,"LXVIII");
    result.put(69,"LXIX");
    result.put(70,"LXX");
    result.put(71, "LXXI");
    result.put(72, "LXXII");
    result.put(73, "LXXIII");
    result.put(74, "LXXIV");
    result.put(75,"LXXV");
    result.put(76,"LXXVI");
    result.put(77,"LXXVII");
    result.put(78,"LXXVIII");
    result.put(79,"LXXIX");
    result.put(80,"LXXX");
    result.put(81, "LXXXI");
    result.put(82, "LXXXII");
    result.put(83, "LXXXIII");
    result.put(84, "LXXXIV");
    result.put(85,"LXXXV");
    result.put(86,"LXXXVI");
    result.put(87,"LXXXVII");
    result.put(88,"LXXXVIII");
    result.put(89,"LXXXIX");
    result.put(90,"XС");
    result.put(91, "XCI");
    result.put(92, "XCII");
    result.put(93, "XCIII");
    result.put(94, "XCIV");
    result.put(95,"XCV");
    result.put(96,"XCVI");
    result.put(97,"XCVII");
    result.put(98,"XCVIII");
    result.put(99,"XCIX");
    result.put(100,"C");
}
}
